name: Deploy Dokka Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure Android environment
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          chmod +x ./gradlew

      - name: Generate Dokka documentation
        run: ./gradlew dokkaGenerate --stacktrace --info

      - name: Verify documentation
        run: |
          [ -d build/dokka/output ] || (echo "ERROR: Docs directory missing" && exit 1)
          [ -f build/dokka/output/index.html ] || (echo "ERROR: Index file missing" && exit 1)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/dokka/output
          force_orphan: true
          keep_files: false
          commit_message: "docs: Update documentation via GitHub Actions"